### ISSUE TITLE
Фогстрим ревью

### ISSUE THREAD

**Issue by nikvst** [akaKAIN/test-auth#1]
1. БД
Сотрудников не обязательно было выносить, а так все ок.

2. settings.py
Часть настроек лучше выносить в отдельные файлы (.json, .yaml, .ini) или переменные окружения и не включать их в репозиторий. Потому что сейчас некоторая приватная информация (SECRET_KEY, например) доступна всем

3. pylint_review.txt
Результат проверки линтером не нужно складывать в файл, необходимо просто читать этот лог и исправлять замечания.

4. Тесты
Не увидел тестов

5. https://github.com/akaKAIN/test-auth/blob/line_3/accounts/forms.py#L45
При работе со сторонним api необходимо обрабатывать исключения (сеть недоступна) и коды ответа сервера (4**ые и 5**ые коды).

6. https://github.com/akaKAIN/test-auth/blob/line_3/validate/views.py#L7
А зачем валидировать email руками, если все есть в django?

7. App Account необходимо было разбить на две. 
Одна бы отвечала за авторизацию/регистрацию, а вторая за отправку сообщений. Тогда и app Validate скорее всего не понадобилась бы

**Comment by akaKAIN** [comment]
Спасибо за оперативное ревью.
Тесты постараюсь в ближайшие несколько часов разобрать и добавить.

**Comment by akaKAIN** [comment]
Добавил тесты.
